import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  FileText, Download, BarChart2, Calendar, TrendingUp, Globe,
  Briefcase, Search, Share2, Megaphone, CheckCircle, Clock,
  Star, Filter, Eye, Trash2, Plus, Printer, X
} from 'lucide-react';

const mockReports = [
  {
    id: 'rpt-1', title: 'Q2 2026 Full Marketing Report', type: 'comprehensive',
    created: '2026-06-01', pages: 24, size: '3.2 MB', status: 'ready',
    scores: { business: 92, health: 88, seo: 91, social: 74, marketing: 89 },
  },
  {
    id: 'rpt-2', title: 'Acme Corp Website Audit Report', type: 'audit',
    created: '2026-05-28', pages: 12, size: '1.8 MB', status: 'ready',
    scores: { business: 0, health: 88, seo: 91, social: 0, marketing: 0 },
  },
  {
    id: 'rpt-3', title: 'May Social Media Performance', type: 'social',
    created: '2026-05-31', pages: 8, size: '1.1 MB', status: 'ready',
    scores: { business: 0, health: 0, seo: 0, social: 74, marketing: 0 },
  },
  {
    id: 'rpt-4', title: 'SEO Keyword & Technical Audit', type: 'seo',
    created: '2026-05-20', pages: 16, size: '2.4 MB', status: 'ready',
    scores: { business: 0, health: 0, seo: 91, social: 0, marketing: 0 },
  },
  {
    id: 'rpt-5', title: 'June Marketing Strategy Plan', type: 'strategy',
    created: '2026-06-05', pages: 19, size: '2.9 MB', status: 'generating',
    scores: { business: 92, health: 88, seo: 91, social: 74, marketing: 89 },
  },
];

const typeConfig = {
  comprehensive: { label: 'Full Report', color: 'from-violet-500 to-purple-600', icon: BarChart2, bg: 'bg-violet-50 text-violet-700 border-violet-200' },
  audit: { label: 'Website Audit', color: 'from-cyan-500 to-blue-500', icon: Globe, bg: 'bg-cyan-50 text-cyan-700 border-cyan-200' },
  social: { label: 'Social Media', color: 'from-pink-500 to-rose-500', icon: Share2, bg: 'bg-pink-50 text-pink-700 border-pink-200' },
  seo: { label: 'SEO Report', color: 'from-emerald-500 to-teal-600', icon: Search, bg: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  strategy: { label: 'Strategy Plan', color: 'from-amber-500 to-orange-500', icon: Megaphone, bg: 'bg-amber-50 text-amber-700 border-amber-200' },
};

const analyticsStats = [
  { label: 'Reports Generated', value: '24', icon: FileText, color: 'from-violet-500 to-purple-600' },
  { label: 'Total Downloads', value: '142', icon: Download, color: 'from-cyan-500 to-blue-500' },
  { label: 'Avg Report Score', value: '83', icon: TrendingUp, color: 'from-emerald-500 to-teal-600' },
  { label: 'This Month', value: '7', icon: Calendar, color: 'from-amber-500 to-orange-500' },
];

const ScorePill = ({ label, score }) => {
  if (!score) return null;
  const color = score >= 80 ? 'bg-emerald-50 text-emerald-600 border-emerald-100' : score >= 55 ? 'bg-amber-50 text-amber-600 border-amber-100' : 'bg-red-50 text-red-600 border-red-100';
  return (
    <span className={`text-[10px] font-bold border rounded-full px-2 py-0.5 ${color}`}>
      {label} {score}
    </span>
  );
};

const Reports = () => {
  const [filter, setFilter] = useState('all');
  const [generating, setGenerating] = useState(false);
  const [reportsList, setReportsList] = useState(mockReports);
  const [previewReport, setPreviewReport] = useState(null);

  const filtered = filter === 'all' ? reportsList : reportsList.filter(r => r.type === filter);

  const handleGenerate = () => {
    setGenerating(true);
    setTimeout(() => {
      const newReport = {
        id: `rpt-${Date.now()}`,
        title: `Auto-Generated Marketing Analysis ${new Date().toLocaleDateString()}`,
        type: 'comprehensive',
        created: new Date().toISOString().split('T')[0],
        pages: 18,
        size: '2.5 MB',
        status: 'ready',
        scores: { business: 85, health: 90, seo: 88, social: 65, marketing: 82 }
      };
      setReportsList(prev => [newReport, ...prev]);
      setGenerating(false);
    }, 2000);
  };

  const handleDownload = (report) => {
    const content = `
=========================================
${report.title.toUpperCase()}
=========================================
Category: ${report.type.toUpperCase()}
Created: ${report.created}
Pages: ${report.pages}
Size: ${report.size}

OVERVIEW SCORES:
${Object.entries(report.scores).map(([k, v]) => v > 0 ? `- ${k.toUpperCase()}: ${v}%` : '').filter(Boolean).join('\n')}

DETAILED MARKETING FINDINGS:
1. Technical Optimization: Secure all endpoints, Compress high-resolution media files.
2. Search Engine Visibility: Focus on high-intent search keywords and title tag length.
3. Social Audience Reach: Use UTM tracking tags for conversion tracking.
4. AI Growth Suggestion: Publish bi-weekly industry reviews to double inbound leads.

Report generated by MarketerAI Platform.
=========================================
`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${report.title.toLowerCase().replace(/ /g, '_')}_report.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handlePrint = (report) => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Print - ${report.title}</title>
          <style>
            body { font-family: 'Inter', sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; }
            .header { border-bottom: 2px solid #8b5cf6; padding-bottom: 20px; margin-bottom: 30px; }
            .title { font-size: 24px; font-weight: bold; color: #0f172a; margin: 0; }
            .meta { font-size: 12px; color: #64748b; margin-top: 5px; }
            .scores { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 15px; margin: 30px 0; }
            .score-card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; text-align: center; }
            .score-val { font-size: 20px; font-weight: 800; color: #8b5cf6; }
            .section { margin-bottom: 30px; }
            .section-title { font-size: 16px; font-weight: bold; border-bottom: 1px solid #f1f5f9; padding-bottom: 5px; margin-bottom: 15px; color: #0f172a; }
            .suggestion { background: #f8fafc; border-left: 4px solid #8b5cf6; padding: 12px; margin-bottom: 10px; font-size: 13px; }
            @media print {
              body { padding: 0; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="title">${report.title}</div>
            <div class="meta">Created on ${report.created} | Pages: ${report.pages} | Category: ${report.type.toUpperCase()}</div>
          </div>
          
          <div class="section">
            <div class="section-title">EXECUTIVE PERFORMANCE OVERVIEW</div>
            <p>This report compiles comprehensive data-driven marketing audits, search visibility scores, speed indices, and social media tracking metrics to evaluate the business's current digital footprint.</p>
            <div class="scores">
              ${Object.entries(report.scores).map(([k, v]) => v > 0 ? `
                <div class="score-card">
                  <div style="font-size: 11px; text-transform: uppercase; color: #64748b; font-weight: 600;">${k}</div>
                  <div class="score-val">${v}%</div>
                </div>
              ` : '').join('')}
            </div>
          </div>

          <div class="section">
            <div class="section-title">KEY SUGGESTIONS & INSIGHTS</div>
            <div class="suggestion">
              <strong>🚀 Focus on high-intent search keywords:</strong> Optimize technical website indices, secure all endpoints, and compressed media files to improve mobile speed by 40%.
            </div>
            <div class="suggestion">
              <strong>📈 Refine audience targeting parameters:</strong> Set up tracking parameters (UTM tags) for paid social campaigns to audit channel conversions accurately.
            </div>
            <div class="suggestion">
              <strong>⚡ Improve load performance:</strong> Leverage server cache optimizations to ensure rapid Time to First Byte (TTFB).
            </div>
          </div>
          
          <script>
            window.onload = function() {
              window.print();
              window.onafterprint = function() { window.close(); };
            }
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  const handleDelete = (id) => {
    if (window.confirm('Delete this report?')) {
      setReportsList(prev => prev.filter(r => r.id !== id));
    }
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-extrabold text-slate-800 font-sans">Reports Center</h1>
          <p className="text-slate-500 text-sm mt-0.5">Download, manage and analyze all your marketing reports</p>
        </div>
        <motion.button
          onClick={handleGenerate}
          disabled={generating}
          whileTap={{ scale: 0.97 }}
          className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-violet-500/20 hover:opacity-95 disabled:opacity-60 transition-all"
        >
          {generating ? (
            <><div className="h-4 w-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Generating...</>
          ) : (
            <><Plus className="h-4 w-4" /> Generate New Report</>
          )}
        </motion.button>
      </div>

      {/* Analytics Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {analyticsStats.map((stat, i) => (
          <motion.div key={stat.label} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.08 }}
            className="bg-white rounded-2xl border border-slate-100 shadow-sm p-4 flex items-center gap-3">
            <div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br ${stat.color} text-white shadow-sm`}>
              <stat.icon className="h-5 w-5" />
            </div>
            <div>
              <p className="text-2xl font-extrabold text-slate-800">{stat.value}</p>
              <p className="text-xs text-slate-400 leading-tight">{stat.label}</p>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Report Analytics Chart */}
      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-6">
        <div className="flex items-center justify-between mb-5">
          <h3 className="text-base font-bold text-slate-800">Report Generation History</h3>
          <span className="text-xs text-slate-400">Last 6 months</span>
        </div>
        <div className="flex items-end gap-3 h-28">
          {[
            { month: 'Jan', count: 2 },
            { month: 'Feb', count: 4 },
            { month: 'Mar', count: 3 },
            { month: 'Apr', count: 6 },
            { month: 'May', count: 5 },
            { month: 'Jun', count: 7 },
          ].map((item, i) => (
            <div key={item.month} className="flex-1 flex flex-col items-center gap-1">
              <span className="text-xs font-bold text-slate-500">{item.count}</span>
              <motion.div
                className="w-full rounded-t-lg bg-gradient-to-t from-violet-500 to-indigo-400"
                initial={{ height: 0 }}
                animate={{ height: `${(item.count / 7) * 100}%` }}
                transition={{ delay: i * 0.1, duration: 0.6, ease: 'easeOut' }}
              />
              <span className="text-[10px] text-slate-400">{item.month}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Filter Tabs + Report List */}
      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
        <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100">
          <div className="flex gap-1 flex-wrap">
            {[
              { id: 'all', label: 'All Reports' },
              { id: 'comprehensive', label: 'Full' },
              { id: 'audit', label: 'Audit' },
              { id: 'seo', label: 'SEO' },
              { id: 'social', label: 'Social' },
              { id: 'strategy', label: 'Strategy' },
            ].map(f => (
              <button key={f.id} onClick={() => setFilter(f.id)}
                className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all ${filter === f.id ? 'bg-violet-100 text-violet-700' : 'text-slate-500 hover:bg-slate-100'}`}>
                {f.label}
              </button>
            ))}
          </div>
          <div className="flex items-center gap-1 text-xs text-slate-400">
            <Filter className="h-3.5 w-3.5" />
            <span>{filtered.length} reports</span>
          </div>
        </div>

        <div className="divide-y divide-slate-50">
          <AnimatePresence>
            {filtered.map((report, i) => {
              const cfg = typeConfig[report.type];
              const Icon = cfg.icon;
              return (
                <motion.div key={report.id}
                  initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
                  transition={{ delay: i * 0.05 }}
                  className="flex flex-col sm:flex-row sm:items-center gap-4 px-5 py-4 hover:bg-slate-50 transition-all"
                >
                  {/* Icon */}
                  <div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br ${cfg.color} text-white shadow-sm`}>
                    <Icon className="h-5 w-5" />
                  </div>

                  {/* Info */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap mb-1">
                      <h4 className="text-sm font-bold text-slate-800 truncate">{report.title}</h4>
                      <span className={`text-[10px] font-bold border rounded-full px-2 py-0.5 ${cfg.bg}`}>{cfg.label}</span>
                      {report.status === 'generating' && (
                        <span className="text-[10px] font-bold border rounded-full px-2 py-0.5 bg-amber-50 text-amber-600 border-amber-200 flex items-center gap-1">
                          <div className="h-1.5 w-1.5 rounded-full bg-amber-500 animate-pulse" /> Generating
                        </span>
                      )}
                    </div>
                    <div className="flex items-center gap-3 text-xs text-slate-400">
                      <span className="flex items-center gap-1"><Calendar className="h-3 w-3" />{report.created}</span>
                      <span>{report.pages} pages</span>
                      <span>{report.size}</span>
                    </div>
                    <div className="flex flex-wrap gap-1 mt-2">
                      {Object.entries(report.scores).map(([key, val]) =>
                        val > 0 ? <ScorePill key={key} label={key.charAt(0).toUpperCase() + key.slice(1)} score={val} /> : null
                      )}
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="flex items-center gap-2 shrink-0">
                    <button onClick={() => setPreviewReport(report)}
                      className="flex items-center gap-1.5 rounded-xl border border-slate-200 px-3 py-2 text-xs font-medium text-slate-600 hover:bg-slate-100 transition-all">
                      <Eye className="h-3.5 w-3.5" /> Preview
                    </button>
                    <motion.button
                      onClick={() => handleDownload(report)}
                      whileTap={{ scale: 0.95 }}
                      disabled={report.status === 'generating'}
                      className="flex items-center gap-1.5 rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 px-3 py-2 text-xs font-semibold text-white shadow-sm hover:opacity-90 disabled:opacity-50 transition-all"
                    >
                      <Download className="h-3.5 w-3.5" /> Download
                    </motion.button>
                    <button onClick={() => handleDelete(report.id)} className="rounded-xl p-2 text-slate-300 hover:text-red-400 hover:bg-red-50 transition-all">
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>
                </motion.div>
              );
            })}
          </AnimatePresence>
        </div>
      </div>

      {/* Report Preview Modal */}
      <AnimatePresence>
        {previewReport && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm">
            <motion.div initial={{ scale: 0.95, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.95, y: 20 }}
              className="w-full max-w-3xl bg-white rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh]">
              
              {/* Modal Header */}
              <div className="bg-gradient-to-r from-violet-600 to-indigo-600 p-6 text-white flex justify-between items-start">
                <div>
                  <span className="text-[10px] font-bold uppercase tracking-wider bg-white/20 px-2.5 py-1 rounded-full">
                    {typeConfig[previewReport.type]?.label || 'Report'}
                  </span>
                  <h2 className="text-lg font-extrabold mt-2">{previewReport.title}</h2>
                  <p className="text-xs text-violet-200 mt-1">Generated on {previewReport.created} | {previewReport.pages} Pages</p>
                </div>
                <button onClick={() => setPreviewReport(null)} className="rounded-xl p-1.5 bg-white/10 hover:bg-white/20 transition-all text-white">
                  <X className="h-5 w-5" />
                </button>
              </div>

              {/* Modal Content */}
              <div className="p-6 overflow-y-auto space-y-6 flex-1 text-left">
                {/* Executive Overview */}
                <div>
                  <h3 className="text-sm font-bold text-slate-800 border-b border-slate-100 pb-2 mb-3">Executive Summary</h3>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    This detailed analysis compiles digital speed, security configurations, content formatting, and keyword tracking metrics. We recommend using these guidelines to optimize marketing campaigns and landing pages.
                  </p>
                </div>

                {/* Scores Overview */}
                <div>
                  <h3 className="text-sm font-bold text-slate-800 border-b border-slate-100 pb-2 mb-3">Audit Scores Summary</h3>
                  <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
                    {Object.entries(previewReport.scores).map(([key, val]) => (
                      <div key={key} className="bg-slate-50 border border-slate-100 rounded-2xl p-3 text-center">
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">{key}</p>
                        <p className={`text-lg font-extrabold mt-1 ${val > 0 ? 'text-violet-600' : 'text-slate-300'}`}>
                          {val > 0 ? `${val}%` : 'N/A'}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Core Audit Findings */}
                <div>
                  <h3 className="text-sm font-bold text-slate-800 border-b border-slate-100 pb-2 mb-3">Key Audit Findings</h3>
                  <div className="space-y-3">
                    {[
                      { title: 'Technical Optimization', desc: 'Secure endpoints, leverage browser caching, and reduce media assets payload sizes.' },
                      { title: 'Search Engine Authority', desc: 'Establish relevant industry backlink metrics and perform on-page technical semantic enhancements.' },
                      { title: 'Audience Segment Engagement', desc: 'Build responsive content funnels across primary channels with dedicated UTM trackers.' }
                    ].map((finding, idx) => (
                      <div key={idx} className="flex gap-3 bg-violet-50/50 border border-violet-100/50 p-3 rounded-2xl">
                        <div className="h-6 w-6 rounded-full bg-violet-100 text-violet-700 flex items-center justify-center text-xs font-bold shrink-0">
                          {idx + 1}
                        </div>
                        <div>
                          <h4 className="text-xs font-bold text-slate-800">{finding.title}</h4>
                          <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">{finding.desc}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Modal Footer */}
              <div className="px-6 py-4 border-t border-slate-100 bg-slate-50 flex justify-between items-center gap-3">
                <button onClick={() => handlePrint(previewReport)}
                  className="flex items-center gap-1.5 rounded-xl border border-slate-200 px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100 bg-white transition-all">
                  <Printer className="h-4 w-4" /> Print Report
                </button>
                <div className="flex gap-2">
                  <button onClick={() => setPreviewReport(null)}
                    className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-150 bg-white transition-all">
                    Close
                  </button>
                  <button onClick={() => handleDownload(previewReport)}
                    className="flex items-center gap-1.5 rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 px-5 py-2 text-xs font-semibold text-white shadow-sm hover:opacity-95 transition-all">
                    <Download className="h-4 w-4" /> Download PDF
                  </button>
                </div>
              </div>

            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Report Features List */}
      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-6">
        <h3 className="text-base font-bold text-slate-800 mb-4 flex items-center gap-2">
          <Star className="h-5 w-5 text-amber-400" /> What's Included in Every Report
        </h3>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {[
            'Executive Summary Dashboard',
            'Business Profile Completeness Score',
            'Website Health & Speed Metrics',
            'SEO Keyword & On-Page Analysis',
            'Social Media Performance Breakdown',
            'AI-Generated Marketing Recommendations',
            '30-Day Action Plan with Priority Tasks',
            'Competitor Benchmark Comparison',
            'ROI Projections & Growth Forecasts',
          ].map((feature, i) => (
            <motion.div key={feature} initial={{ opacity: 0, x: -5 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.06 }}
              className="flex items-center gap-2 text-sm text-slate-600">
              <CheckCircle className="h-4 w-4 text-emerald-500 shrink-0" />
              {feature}
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Reports;
