import html2pdf from 'html2pdf.js';

export const generatePDF = (reportData, type) => {
  const dateStr = new Date().toLocaleString();
  const title = reportData.title || reportData.website_url || reportData.business_name || `${type} Report`;
  
  // Base HTML structure
  const element = document.createElement('div');
  element.innerHTML = `
    <div style="font-family: 'Inter', sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; background-color: #ffffff; max-width: 800px; margin: 0 auto;">
      <div style="border-bottom: 2px solid #8b5cf6; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center;">
        <div>
          <h1 style="font-size: 24px; font-weight: bold; color: #0f172a; margin: 0;">${title}</h1>
          <p style="font-size: 12px; color: #64748b; margin-top: 5px;">
            Generated: ${dateStr} | Module: ${type}
          </p>
        </div>
        <div style="font-size: 18px; font-weight: 800; color: #8b5cf6; letter-spacing: -0.5px;">MarketerAI ✨</div>
      </div>

      <!-- Module Specific Content will be appended here -->
      <div id="pdf-content"></div>

      <div style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 10px; color: #94a3b8;">
        This document is securely generated by the AI Digital Marketing Consultant SaaS Platform.
      </div>
    </div>
  `;

  const contentDiv = element.querySelector('#pdf-content');

  // Generic Scores Section
  const scores = [];
  if (reportData.health_score) scores.push({ label: 'Health Score', value: reportData.health_score });
  if (reportData.seo_score) scores.push({ label: 'SEO Score', value: reportData.seo_score });
  if (reportData.performance_score) scores.push({ label: 'Performance', value: reportData.performance_score });
  if (reportData.social_score) scores.push({ label: 'Social Media', value: reportData.social_score });
  if (reportData.marketing_score) scores.push({ label: 'Marketing', value: reportData.marketing_score });
  if (reportData.completeness_score) scores.push({ label: 'Completeness', value: reportData.completeness_score });
  if (reportData.strategy_score) scores.push({ label: 'Strategy Score', value: reportData.strategy_score });

  if (scores.length > 0) {
    contentDiv.innerHTML += `
      <div style="margin-bottom: 35px;">
        <h3 style="font-size: 14px; font-weight: 700; border-bottom: 2px solid #f1f5f9; padding-bottom: 6px; margin-bottom: 15px; color: #0f172a; text-transform: uppercase;">Performance Scores</h3>
        <div style="display: flex; flex-wrap: wrap; gap: 15px;">
          ${scores.map(s => `
            <div style="border: 1px solid #e2e8f0; border-radius: 12px; padding: 15px; text-align: center; background: #f8fafc; min-width: 120px;">
              <div style="font-size: 10px; text-transform: uppercase; color: #64748b; font-weight: 700; margin-bottom: 5px;">${s.label}</div>
              <div style="font-size: 24px; font-weight: 800; color: #8b5cf6;">${s.value}%</div>
            </div>
          `).join('')}
        </div>
      </div>
    `;
  }

  // Recommendations / Suggestions Section
  const suggestions = reportData.suggestions || reportData.improvement_suggestions || reportData.growth_suggestions;
  if (suggestions && suggestions.length > 0) {
    contentDiv.innerHTML += `
      <div style="margin-bottom: 35px; page-break-inside: avoid;">
        <h3 style="font-size: 14px; font-weight: 700; border-bottom: 2px solid #f1f5f9; padding-bottom: 6px; margin-bottom: 15px; color: #0f172a; text-transform: uppercase;">Recommendations & Action Plan</h3>
        <ul style="list-style-type: none; padding-left: 0; margin: 0;">
          ${suggestions.map(s => `
            <li style="background: #f8fafc; border-left: 4px solid #8b5cf6; padding: 12px; margin-bottom: 10px; font-size: 13px; border-radius: 0 8px 8px 0;">
              ${typeof s === 'object' ? s.message || s.text || JSON.stringify(s) : s}
            </li>
          `).join('')}
        </ul>
      </div>
    `;
  }

  // Detailed Metrics Based on Type
  let metricsHTML = '';
  
  if (type === 'Website Audit' || type === 'SEO Audit') {
    metricsHTML = `
      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 35px;">
        <div>
          <div style="display: flex; justify-content: space-between; border-bottom: 1px solid #f1f5f9; padding: 6px 0; font-size: 13px;">
            <span style="color: #64748b; font-weight: 500;">Load Time</span>
            <span style="color: #1e293b; font-weight: 600;">${reportData.load_time || 'N/A'}</span>
          </div>
          <div style="display: flex; justify-content: space-between; border-bottom: 1px solid #f1f5f9; padding: 6px 0; font-size: 13px;">
            <span style="color: #64748b; font-weight: 500;">Secure HTTPS</span>
            <span style="color: #1e293b; font-weight: 600;">${reportData.secure ? 'Yes' : 'No'}</span>
          </div>
        </div>
        <div>
          <div style="display: flex; justify-content: space-between; border-bottom: 1px solid #f1f5f9; padding: 6px 0; font-size: 13px;">
            <span style="color: #64748b; font-weight: 500;">Mobile Friendly</span>
            <span style="color: #1e293b; font-weight: 600;">${reportData.mobile_friendly ? 'Yes' : 'No'}</span>
          </div>
          <div style="display: flex; justify-content: space-between; border-bottom: 1px solid #f1f5f9; padding: 6px 0; font-size: 13px;">
            <span style="color: #64748b; font-weight: 500;">Open Graph</span>
            <span style="color: #1e293b; font-weight: 600;">${reportData.open_graph ? 'Yes' : 'No'}</span>
          </div>
        </div>
      </div>
    `;
  } else if (type === 'Social Media') {
    metricsHTML = `
      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 35px;">
        <div>
          <div style="display: flex; justify-content: space-between; border-bottom: 1px solid #f1f5f9; padding: 6px 0; font-size: 13px;">
            <span style="color: #64748b; font-weight: 500;">Platforms Analyzed</span>
            <span style="color: #1e293b; font-weight: 600;">${reportData.platforms_analyzed || '0'}</span>
          </div>
        </div>
        <div>
          <div style="display: flex; justify-content: space-between; border-bottom: 1px solid #f1f5f9; padding: 6px 0; font-size: 13px;">
            <span style="color: #64748b; font-weight: 500;">Missing Elements</span>
            <span style="color: #1e293b; font-weight: 600;">${(reportData.missing_elements || []).length}</span>
          </div>
        </div>
      </div>
    `;
  } else if (type === 'Business Profile') {
    metricsHTML = `
      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 35px;">
        <div>
          <div style="display: flex; justify-content: space-between; border-bottom: 1px solid #f1f5f9; padding: 6px 0; font-size: 13px;">
            <span style="color: #64748b; font-weight: 500;">Industry</span>
            <span style="color: #1e293b; font-weight: 600;">${reportData.industry_type || 'N/A'}</span>
          </div>
          <div style="display: flex; justify-content: space-between; border-bottom: 1px solid #f1f5f9; padding: 6px 0; font-size: 13px;">
            <span style="color: #64748b; font-weight: 500;">Location</span>
            <span style="color: #1e293b; font-weight: 600;">${reportData.business_location || 'N/A'}</span>
          </div>
        </div>
        <div>
          <div style="display: flex; justify-content: space-between; border-bottom: 1px solid #f1f5f9; padding: 6px 0; font-size: 13px;">
            <span style="color: #64748b; font-weight: 500;">Website</span>
            <span style="color: #1e293b; font-weight: 600;">${reportData.website_url || 'N/A'}</span>
          </div>
          <div style="display: flex; justify-content: space-between; border-bottom: 1px solid #f1f5f9; padding: 6px 0; font-size: 13px;">
            <span style="color: #64748b; font-weight: 500;">Target Audience</span>
            <span style="color: #1e293b; font-weight: 600;">${reportData.target_audience || 'N/A'}</span>
          </div>
        </div>
      </div>
    `;
  }

  if (metricsHTML) {
    contentDiv.innerHTML = `
      <h3 style="font-size: 14px; font-weight: 700; border-bottom: 2px solid #f1f5f9; padding-bottom: 6px; margin-bottom: 15px; color: #0f172a; text-transform: uppercase;">Analysis Breakdown</h3>
      ${metricsHTML}
    ` + contentDiv.innerHTML;
  }

  const opt = {
    margin:       0.5,
    filename:     `${title.toLowerCase().replace(/\s+/g, '_')}_report.pdf`,
    image:        { type: 'jpeg', quality: 0.98 },
    html2canvas:  { scale: 2, useCORS: true },
    jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
  };

  html2pdf().set(opt).from(element).save();
};

export const printReport = (reportData, type) => {
  const dateStr = new Date().toLocaleString();
  const title = reportData.title || reportData.website_url || reportData.business_name || `${type} Report`;
  const printWindow = window.open('', '_blank');
  const htmlStr = `
    <html>
      <head>
        <title>Print - ${title}</title>
        <style>
          body { font-family: 'Inter', sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; background-color: #ffffff; }
          .header { border-bottom: 2px solid #8b5cf6; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
          @media print { body { padding: 0; } }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1 style="margin:0;">${title}</h1>
            <p style="margin:5px 0 0 0; color: #64748b;">Generated: ${dateStr} | Module: ${type}</p>
          </div>
          <div style="font-size: 18px; font-weight: 800; color: #8b5cf6;">MarketerAI ✨</div>
        </div>
        <div style="margin-bottom: 20px;">
          <h3>Please use the "Download PDF" option for a highly formatted, rich PDF document.</h3>
          <p>A basic print view is provided here for convenience.</p>
        </div>
        <script>
          window.onload = function() { window.print(); window.onafterprint = function() { window.close(); }; }
        </script>
      </body>
    </html>
  `;
  printWindow.document.write(htmlStr);
  printWindow.document.close();
};
